---
title: "M/STAT 502 Course Calendar"
output:
  html_document:
      theme: cerulean
      toc: TRUE
      toc_depth: 2
      toc_float: TRUE
      css: styles.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### [Back to M/STAT 502 syllabus...](index.html)

STAT 502 aims to cover Chapters 5--9 in Casella and Berger, continuing from STAT 501. 

# Week 1

#### Mon Jan 11

* Introductions to the course
* Section 5.1: Basic concepts of random samples
* Section 5.2: Sums of random variables from a random sample

#### Wed Jan 13

* Section 5.3: Sampling from the normal distribution

#### Fri  Jan 15

* Section 5.3 (cont): Sampling from the normal distribution

---

# Week 2

#### Mon Jan 18

_Martin Luther King Day: No class_

#### Wed Jan 20

* Section 5.4: Order statistics
* **Homework 1 due** (Sections 5.1-1.3) in [Gradescope](https://www.gradescope.com) by 5:00pm

#### Fri Jan 22

* Section 5.4 (cont): Order statistics

---

# Week 3

#### Mon Jan 25

* Section 5.5: Convergence concepts


#### Wed Jan 27

* No class
* Video: Convergence in Distribution
* Video: Central Limit Theorem
* **_QUIZ 1_** in [Gradescope](https://www.gradescope.com) 11am--1pm (45 min time limit): Sections 5.1-5.3

#### Fri Jan 29

* Section 5.5 (cont): Convergence concepts
* (Skip Section 5.6)

---

# Week 4

#### Mon Feb 1

* Section 7.1-7.2: Methods of finding estimators - method of moments

#### Wed Feb 3

* Section 6.3.1: The likelihood function
* Section 7.2 (cont): Methods of finding estimators - maximum likelihood

#### Fri Feb 5

* Section 7.2 (cont): Methods of finding estimators - maximum likelihood
* **Homework 2 due** (Sections 5.4-5.5) in [Gradescope](https://www.gradescope.com) by 5:00pm

---

# Week 5

#### Mon Feb 8

* Section 7.2 (cont): Methods of finding estimators - Bayes

#### Wed Feb 10

* No class
* Video: Derivation of Beta-Binomial Bayes Estimator
* Video: Beta-Binomial Bayes Estimator Example
* Video: Conjugate Families
* **_QUIZ 2_** in [Gradescope](https://www.gradescope.com) 11am--1pm (45 min time limit): Sections 5.4-5.5

#### Fri Feb 12

* Section 7.3: Methods of evaluating estimators

---

# Week 6

#### Mon Feb 15

_President's Day: No class_

#### Wed Feb 17

* Section 7.3 (cont): Methods of evaluating estimators

#### Fri Feb 19

* Sections 6.1-6.2: Sufficiency principle
* **Homework 3 due** (Sections 7.1-7.2) in [Gradescope](https://www.gradescope.com) by 5:00pm

---

# Week 7

#### Mon Feb 22

* Sections 6.2 (cont), Section 7.3.3: Sufficiency principle


#### Wed Feb 24

* No class
* Video: Ancillary Statistics
* Video: Complete Statistics
* Video: Example: Complete Sufficient Statistic
* **_QUIZ 3_** in [Gradescope](https://www.gradescope.com) 11am--6pm (45 min time limit): Sections 7.1-7.2

#### Fri Feb 26

* Sections 6.2 (cont), Section 7.3.3: Sufficiency principle

---

# Week 8

#### Mon Mar 1

* Sections 6.2 (cont), Section 7.3.3: Sufficiency principle

#### Wed Mar 3

* Section 10.1: Asymptotic evaluations --- point estimation

#### Fri Mar 5

* Section 7.3.4: Loss function optimality
* **Homework 4 due** (Sections 7.3.1-7.3.4, 6.2, 10.1) in [Gradescope](https://www.gradescope.com) by 5:00pm

---

# Week 9

#### Mon Mar 8

* Simulation example: Consistency
* Section 8.1: Introduction to hypothesis testing
* **Project proposal** due in [Gradescope](https://www.gradescope.com) by 5:00pm


#### Wed Mar 10

* No class
* **_QUIZ 4_** in [Gradescope](https://www.gradescope.com) 11am--1pm (45 min time limit): Sections 7.3.1-7.3.4, 6.2, 10.1


#### Fri Mar 12

* Section 8.3.1: Methods for evaluating tests

---

# Week 10

#### Mon Mar 15

* Section 8.3.1 (cont): Methods for evaluating tests

#### Wed Mar 17

* Section 8.3.1 (cont): Methods for evaluating tests


#### Fri Mar 19

* Section 8.2.1: Likelihood ratio tests
* **Homework 5 due** (Sections 8.1 and 8.3.1) in [Gradescope](https://www.gradescope.com) by 5:00pm

---

# Week 11

#### Mon Mar 22

* Section 8.2.1 (cont): Likelihood ratio tests

#### Wed Mar 24

* No class
* **_QUIZ 5_** in [Gradescope](https://www.gradescope.com) 11am--1pm (45 min time limit): Sections 8.1 and 8.3.1

#### Fri Mar 26

* Section 8.3.2: Uniformly most powerful tests

---

# Week 12

#### Mon Mar 29

* Section 8.3.2 (cont) and 8.3.4: Uniformly most powerful tests and p-values

#### Wed Mar 31

* Section 9.1: Introduction to interval estimation

#### Fri Apr 2

* _University Day: No class_
* **Homework 6 due** (Sections 8.2.1, 8.3.2, and 8.3.4) in [Gradescope](https://www.gradescope.com) by 5:00pm


---

# Week 13

#### Mon Apr 5

* Section 9.2: Methods of finding interval estimators
* **Draft project report** due in [Gradescope](https://www.gradescope.com) by 5:00pm

#### Wed Apr 7

* No class
* **_QUIZ 6_** in [Gradescope](https://www.gradescope.com) 11am--1pm (45 min time limit): Sections 8.2.1, 8.3.2, and 8.3.4


#### Fri Apr 9

* Section 9.2 (cont): Methods of finding interval estimators

---

# Week 14

#### Mon Apr 12

* Section 9.2 (cont): Methods of finding interval estimators

#### Wed Apr 14

* Section 9.3: Methods of evaluating interval estimators


#### Fri Apr 16

* Section 9.3 (cont): Methods of evaluating interval estimators
* **Final project report** due in [Gradescope](https://www.gradescope.com) by 5:00pm

# Week 15

#### Mon Apr 19

* Synthesize and summarize concepts from M/STAT 501-502
* **Homework 7 due** in [Gradescope](https://www.gradescope.com) by 5:00pm


#### Wed Apr 21

* Project presentations

#### Fri Apr 23

* Project presentations
* **Optional _QUIZ 7_** in [Gradescope](https://www.gradescope.com) 8am--5pm (45 min time limit)
    - Quizzes 1--6 comprise your quiz grade for this course, where the lowest grade from Quizzes 1--6 will be dropped. If your score on Quiz 7 is higher than the second lowest score from Quizzes 1--6 (i.e., the lowest quiz score that counts towards your grade), then your score on that quiz will be replaced by your score on this quiz. If you do not take Quiz 7, or if your score on Quiz 7 is lower than the second lowest score from Quizzes 1--6, then your grade will not change.


# Week 16

Finals week: Take-home final exam released in D2L at 8:00am on Monday, April 26; due in [Gradescope](https://www.gradescope.com) by 5:00pm on Thursday, April 29.



